// AUTHORED-BY Claude Opus 4.8 (Fable unavailable) — re-review/upgrade candidate
//
// authenticated-fetch.ts — `toAuthenticatedFetch(session)`: turn a {@link RestoredSession}
// into a DPoP-AUTHENTICATED, refresh-capable `fetch`. Every request the returned fetch
// makes carries `Authorization: DPoP <accessToken>` plus a FRESH per-request DPoP proof
// signed by the session's bound (non-extractable) key — so the suite's apps (PM, the vite
// pod-apps, the elk/excalidraw/etc forks) stop hand-rolling this auth-attaching fetch and
// share ONE audited implementation, exactly as they already share `restoreSession`.
//
// Generalised from the elk fork's `authedFetchFromRestoredSession`
// (`app/solid/session.ts`, commit 705bac4c) into this package's public API. The elk version
// took a narrowed `Pick<RestoredSession, 'accessToken' | 'dpopHandle'>`; here we take the
// package's full {@link RestoredSession} (and read only what the proof needs) so the call
// site reads as "the restored session → its authed fetch".
//
// ─── Security invariants (do not weaken — every request carries a credential) ────────
//  • DPoP-BOUND, never bare Bearer: the proof is generated by oauth4webapi from the
//    session's `dpopHandle`, which `restoreSession` built around the PERSISTED,
//    non-extractable ES256 key. We NEVER hand-roll a DPoP proof or the Authorization
//    header — we DELEGATE both to oauth4webapi's `protectedResourceRequest` (the same
//    vetted library that minted the handle and the access token).
//  • The access token is captured PER-FETCH-INSTANCE in a closure, never on a shared
//    global. A returned fetch is bound to exactly ONE session's credential. A caller
//    that switches users MUST build a NEW authed fetch (and drop the old one) — see the
//    cross-user-token-reuse note in the README; this function does not own that lifecycle.
//  • STALE auth headers on the incoming request are STRIPPED before each send, so a
//    caller cannot accidentally (or maliciously) pin a different `Authorization`/`DPoP`
//    header onto a request that this fetch is meant to authenticate.
//  • BOUNDED retries — at most one DPoP-nonce retry per returned-fetch invocation AND at
//    most one token-refresh retry; a second 401 after a fresh token does NOT loop (it
//    surfaces the failure).
//  • CONCURRENCY-SAFE refresh — N requests that 401 at the same time cause at MOST ONE
//    refresh (a single shared in-flight promise), and the captured credential only ever
//    moves FORWARD: a refresh result is committed only if `cred` has not already advanced
//    past the credential that 401'd (compare-and-set), so a slower refresh can never clobber
//    a newer token with an older one and force stale-token reuse. This holds UNIFORMLY for
//    BOTH 401 shapes — a RETURNED bare-401 Response AND a THROWN `invalid_token` challenge —
//    because each compares against the SNAPSHOT the failed send used, never the (possibly
//    already-advanced) live credential.
//  • The access/refresh tokens are NEVER logged.

import * as oauth from "oauth4webapi";
import type { RestoredSession } from "./restore-session.js";

const isLoopback = (host: string): boolean =>
  host === "localhost" || host === "127.0.0.1" || host === "[::1]";

/**
 * The live DPoP credential a request actually sends with: the access token plus the
 * oauth4webapi DPoP handle bound to the session's non-extractable key. A
 * {@link RestoredSession} is a superset of this; {@link toAuthenticatedFetch} reads only
 * these two fields per request, and a {@link RefreshAuthenticatedFetch} re-mints them.
 */
export type AuthenticatedFetchCredential = Pick<RestoredSession, "accessToken" | "dpopHandle">;

/**
 * A SILENT re-mint of the live credential, called ONCE when a request gets a 401
 * (expired/invalid access token). Returns a fresh {@link AuthenticatedFetchCredential}
 * (a full {@link RestoredSession} satisfies it), or `null`/`undefined` when the refresh
 * itself fails (dead/revoked refresh token, transient blip) so the fetch fails closed
 * rather than looping. Typically wraps {@link restoreSession} bound to the same
 * store/issuer/clientId — a token-endpoint fetch, NEVER a popup/iframe.
 */
export type RefreshAuthenticatedFetch = () => Promise<
  AuthenticatedFetchCredential | null | undefined
>;

/** Options for {@link toAuthenticatedFetch}. */
export interface ToAuthenticatedFetchOptions {
  /**
   * OPTIONAL silent refresh: when a request 401s (expired/invalid access token), this is
   * run ONCE to re-mint a fresh credential, which is adopted (so subsequent requests on
   * this fetch use the fresh token too) and the request is retried ONCE. Omit it for a
   * single-shot fetch that simply propagates a 401. See {@link RefreshAuthenticatedFetch}.
   */
  refresh?: RefreshAuthenticatedFetch;
  /**
   * OPTIONAL underlying fetch oauth4webapi uses to send each request. Defaults to the
   * global fetch. A test seam, and a hook for apps that wrap fetch (an SSRF-guarded fetch,
   * the reactive-auth patched global) — note the DPoP proof + Authorization header are
   * added by oauth4webapi REGARDLESS of which fetch transports the bytes.
   */
  fetch?: typeof fetch;
  /**
   * Enable oauth4webapi's `allowInsecureRequests` for `localhost` / `127.0.0.1` / `[::1]`
   * targets only (dev CSS over HTTP). Remote HTTPS targets are unaffected, and a
   * non-loopback HTTP target is never allowed. Default `false`.
   */
  allowInsecureLoopback?: boolean;
}

/**
 * oauth4webapi's `customFetch` is invoked with `(url, options)` where `options` is a
 * superset of `RequestInit` it constructed; the app's standard `fetch` accepts it at
 * runtime. We adapt it with a thin wrapper (mirrors restore-session.ts) so no unsafe cast
 * is needed and the runtime contract is explicit.
 */
type OauthCustomFetch = (
  url: string,
  options: oauth.CustomFetchOptions<string, unknown>,
) => Promise<Response>;

/**
 * Whether an error (thrown by oauth4webapi) or a returned response signals the access
 * token is EXPIRED / INVALID — a `WWWAuthenticateChallengeError` (e.g. `invalid_token`) or
 * a bare 401 carry `.status === 401`. Either warrants ONE silent refresh + retry. A
 * DPoP-nonce challenge is handled separately and is NOT a token-expiry.
 */
function isTokenExpiry(err: unknown): boolean {
  return typeof err === "object" && err !== null && (err as { status?: unknown }).status === 401;
}

/**
 * Build a DPoP-AUTHENTICATED, optionally REFRESH-CAPABLE `fetch` from a
 * {@link RestoredSession}. Every request carries `Authorization: DPoP <accessToken>` and a
 * fresh per-request DPoP proof signed by the session's bound (non-extractable) key.
 *
 * The auth is attached by oauth4webapi's `protectedResourceRequest` driven by the session's
 * `dpopHandle` (built INSIDE `restoreSession` from the persisted key) and `accessToken` — we
 * never hand-roll a proof or header.
 *
 * Two DISTINCT bounded retries, in order:
 *  1. DPoP-NONCE retry (RFC 9449 §8): the server may answer the first DPoP request with a
 *     `use_dpop_nonce` challenge; the handle captures the nonce, so we retry ONCE with it
 *     primed. The nonce retry is bounded to ONCE PER returned-fetch invocation — even across
 *     the post-refresh re-send — so the contract is exactly one nonce retry per call, not one
 *     per send-attempt. This does NOT consume the token-refresh retry.
 *  2. TOKEN-REFRESH retry: the captured access token is short-lived. On a 401 (an
 *     `invalid_token` challenge OR a bare-401 response) — when a {@link
 *     ToAuthenticatedFetchOptions.refresh} is supplied — we run it ONCE to silently re-mint
 *     a fresh credential, adopt it (so subsequent requests use the fresh token too), and
 *     retry the request ONCE. If `refresh` is absent or itself fails → the 401 propagates
 *     (no loop).
 *
 * CONCURRENCY: many requests on the same returned fetch can 401 simultaneously. They share a
 * SINGLE in-flight refresh (the first 401'd request starts it; the rest await the same
 * promise), so N concurrent 401s trigger at most ONE refresh. The captured credential is only
 * ever advanced FORWARD via compare-and-set, so a refresh that resolves late cannot overwrite
 * a credential a newer refresh already installed (no stale-token reuse).
 *
 * The returned function matches the Fetch API surface (`fetch(input, init)`), adapting it to
 * `protectedResourceRequest`'s `(accessToken, method, url, headers, body, opts)` shape.
 */
export function toAuthenticatedFetch(
  session: RestoredSession,
  options: ToAuthenticatedFetchOptions = {},
): typeof fetch {
  const { refresh, fetch: appFetch, allowInsecureLoopback } = options;

  // The CAPTURED credential — mutable so a successful silent refresh updates it in place,
  // and every later request on this fetch uses the fresh token (not the expired original).
  // It is only ever advanced FORWARD (compare-and-set in `refreshCredential`), so a slow
  // refresh can never clobber a newer credential a concurrent refresh already installed.
  let cred: AuthenticatedFetchCredential = {
    accessToken: session.accessToken,
    dpopHandle: session.dpopHandle,
  };

  // The SINGLE in-flight refresh shared by all requests that 401 at the same time. The first
  // 401'd request that finds none in flight starts it; every other concurrent 401 awaits the
  // SAME promise — so N concurrent 401s cause at most ONE refresh. Cleared (back to null) when
  // the refresh settles, so a LATER (genuine, post-expiry) 401 can start a fresh one.
  let inFlightRefresh: Promise<AuthenticatedFetchCredential | null> | null = null;

  // Run the injected silent refresh, coalescing concurrent callers onto one shared promise and
  // committing the result via compare-and-set so `cred` only moves forward. `usedCred` is the
  // credential the failed request actually sent with; if `cred` has ALREADY advanced past it
  // (another request's refresh landed first) we skip the refresh entirely and reuse the newer
  // `cred`. Returns the credential to retry with, or null when refresh failed.
  const refreshCredential = (
    usedCred: AuthenticatedFetchCredential,
    doRefresh: RefreshAuthenticatedFetch,
  ): Promise<AuthenticatedFetchCredential | null> => {
    // Another concurrent refresh already advanced the credential past the one that 401'd —
    // no need to refresh again; retry with the credential that's already fresh.
    if (cred !== usedCred) return Promise.resolve(cred);
    // Join the in-flight refresh if one is already running for this stale credential.
    if (inFlightRefresh) return inFlightRefresh;
    // Start the single shared refresh. Commit (compare-and-set) only while still settling so a
    // late-resolving refresh cannot overwrite a credential a newer refresh already installed.
    const run = (async (): Promise<AuthenticatedFetchCredential | null> => {
      let fresh: AuthenticatedFetchCredential | null | undefined;
      try {
        fresh = await doRefresh();
      } catch {
        // Refresh itself threw — fail-closed, no loop.
        return null;
      }
      if (!fresh) return null;
      const next: AuthenticatedFetchCredential = {
        accessToken: fresh.accessToken,
        dpopHandle: fresh.dpopHandle,
      };
      // Compare-and-set: only adopt if nothing advanced `cred` while we were refreshing.
      if (cred === usedCred) cred = next;
      // Return the live `cred` (it may already be newer if a concurrent refresh won the race)
      // so every joiner retries with the freshest credential, never a stale one.
      return cred;
    })();
    inFlightRefresh = run;
    // Clear the in-flight slot once settled so a future (later-expiry) 401 starts a new one.
    void run.finally(() => {
      if (inFlightRefresh === run) inFlightRefresh = null;
    });
    return run;
  };

  return async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    // Normalise the Fetch API call through a SINGLE Request instance so the body bytes and
    // the Content-Type header (e.g. a multipart/form-data boundary) derive from the SAME
    // serialization — re-serializing the body through a second Request can mint a DIFFERENT
    // boundary than a header copied from the original. A `Request` carries its own
    // method/headers/body, overridden by an explicit `init`.
    const req = new Request(input, init);
    const method = req.method;
    const url = new URL(req.url);
    const headers = new Headers(req.headers);
    // protectedResourceRequest sets Authorization + DPoP itself; strip any stale ones the
    // caller put on the request so they cannot override the session's auth.
    headers.delete("authorization");
    headers.delete("dpop");
    // Read the body ONCE from the SAME req (GET/HEAD have none) so the bytes match the
    // headers (incl. the boundary in any Content-Type set by the Request body serialization).
    let body: ArrayBuffer | undefined;
    if (method !== "GET" && method !== "HEAD") {
      const ab = await req.arrayBuffer();
      body = ab.byteLength > 0 ? ab : undefined;
    }

    // The per-call HTTP options oauth4webapi uses: the request's abort signal, the optional
    // app fetch (adapted to customFetch), and the loopback-only insecure allowance.
    const http: oauth.ProtectedResourceRequestOptions = {};
    if (req.signal) http.signal = req.signal;
    if (appFetch) {
      const custom: OauthCustomFetch = (u, opts) => appFetch(u, opts as RequestInit);
      http[oauth.customFetch] = custom;
    }
    if (allowInsecureLoopback && isLoopback(url.hostname)) {
      http[oauth.allowInsecureRequests] = true;
    }

    // The credential a send used — captured so the post-401 path can compare-and-set against
    // it (and so a single send reads ONE consistent {token, handle} pair even if `cred`
    // advances mid-flight from a concurrent refresh).
    const send = (sendCred: AuthenticatedFetchCredential): Promise<Response> =>
      oauth.protectedResourceRequest(
        sendCred.accessToken,
        method,
        url,
        // A fresh Headers per send so a retry never inherits a header the previous send
        // mutated; protectedResourceRequest adds Authorization + DPoP onto this copy.
        new Headers(headers),
        body,
        { ...http, DPoP: sendCred.dpopHandle },
      );

    // The DPoP-nonce retry is bounded to ONCE PER returned-fetch INVOCATION (not once per
    // send-attempt). `attempt()` is reused after a token refresh, so this flag carries the
    // single-nonce-retry budget ACROSS that re-send — matching the documented "one nonce
    // retry per call" contract instead of allowing one before AND one after the refresh.
    let nonceRetryUsed = false;

    // The credential the MOST RECENT `attempt()` send used, recorded so the post-401 path can
    // compare-and-set against the EXACT credential that failed — INCLUDING the THROWN-401 shape
    // (oauth4webapi throws an `invalid_token` challenge rather than returning a 401 Response).
    // Reading this snapshot instead of the live `cred` is load-bearing: between sending the
    // request and seeing it fail, a CONCURRENT request's refresh may have advanced `cred`, so a
    // request that failed with an OLD token must NOT be treated as if it failed with the fresh
    // one — that would trigger a redundant refresh or skip reusing a peer's already-fresh token.
    let lastSendCred: AuthenticatedFetchCredential = cred;

    // One send of the request, returning the credential it actually used alongside the
    // Response, with the (invocation-bounded) DPoP-nonce retry folded in. Resolves to a
    // Response (incl. a bare 401 a server returns without a parseable challenge) or throws.
    // BOTH outcomes record the sending credential in `lastSendCred` first, so the thrown-401
    // path can read the same snapshot the returned-401 path gets via `usedCred`.
    const attempt = async (): Promise<{
      res: Response;
      usedCred: AuthenticatedFetchCredential;
    }> => {
      // Snapshot the live credential ONCE per attempt so the retry's compare-and-set is
      // against the exact credential this attempt sent with — recorded for the thrown path too.
      const usedCred = cred;
      lastSendCred = usedCred;
      try {
        return { res: await send(usedCred), usedCred };
      } catch (err) {
        // One DPoP-nonce retry — but only if the per-invocation budget is unspent.
        if (oauth.isDPoPNonceError(err) && !nonceRetryUsed) {
          nonceRetryUsed = true;
          // The nonce-retry re-sends with the SAME snapshot; `lastSendCred` already holds it.
          return { res: await send(usedCred), usedCred };
        }
        throw err;
      }
    };

    // Run the request, then — ONCE — refresh-on-401 + retry. We catch both shapes of a 401:
    // a thrown WWWAuthenticateChallengeError (invalid_token) and a returned bare-401 Response.
    // Both feed the SAME snapshot into refreshAndRetry — the returned path via `usedCred`, the
    // thrown path via `lastSendCred` — so the compare-and-set discipline is identical for each.
    try {
      const { res, usedCred } = await attempt();
      if (res.status === 401 && refresh) {
        return (await refreshAndRetry(usedCred, refresh)) ?? res;
      }
      return res;
    } catch (err) {
      if (isTokenExpiry(err) && !oauth.isDPoPNonceError(err) && refresh) {
        // The thrown-401 path: refresh against the SNAPSHOT the failed send actually used
        // (`lastSendCred`), NOT the live `cred` — which a concurrent peer's refresh may have
        // already advanced. This gives the thrown shape the SAME compare-and-set discipline as
        // the returned-401 path (only refresh if `cred === usedCred`; `cred` only moves forward;
        // N concurrent failures → one refresh; a peer's fresh token is reused, not re-minted).
        const retried = await refreshAndRetry(lastSendCred, refresh);
        if (retried) return retried;
      }
      throw err;
    }

    // Refresh (coalesced + compare-and-set) the credential the failed request used, then retry
    // the request ONCE with the resulting (always forward-only) credential. Returns the retried
    // Response, or `null` when refresh failed / the retry still 401s (caller then propagates the
    // original 401 — no loop).
    async function refreshAndRetry(
      usedCred: AuthenticatedFetchCredential,
      doRefresh: RefreshAuthenticatedFetch,
    ): Promise<Response | null> {
      const fresh = await refreshCredential(usedCred, doRefresh);
      if (!fresh) return null;
      try {
        // `attempt()` re-reads the (now-advanced) live `cred`, so the retry uses the fresh
        // credential; the per-invocation nonce budget is shared, so no extra nonce retry here.
        const { res } = await attempt();
        // A second 401 after a fresh token → do NOT loop; let the caller see the failure.
        return res.status === 401 ? null : res;
      } catch (retryErr) {
        // Only SUPPRESS a SECOND auth failure (another 401 / token-expiry challenge): return
        // null so the ORIGINAL 401 propagates and we do NOT loop. RETHROW any UNRELATED retry
        // error (network, 5xx, parse, DPoP-nonce) so a real failure surfaces as itself rather
        // than being masked as the original 401. `attempt()` folds in its own single
        // DPoP-nonce retry, so a nonce error here is terminal — but it is not a token-expiry,
        // so it must rethrow, not be silently swallowed.
        if (isTokenExpiry(retryErr) && !oauth.isDPoPNonceError(retryErr)) return null;
        throw retryErr;
      }
    }
  };
}
